services:
  my-db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sales
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
volumes:
  data:
