use sales;
DROP TABLE sales;
DROP TABLE inventory;
DROP TABLE products;
DROP TABLE manufacturers;
DROP TABLE customers;
DROP TABLE employees;
DROP VIEW sales_summary;
DROP VIEW employee_report;
DROP VIEW model_report;